### ISSUE TITLE
Code block bug

### ISSUE THREAD

**Issue by supun-io** [hyvor/blogs#242]
When a new code block is created, it adds two lines. 

- [x] It should be one line

<img width="755" alt="image" src="https://github.com/hyvor/HyvorBlogs/assets/44988673/8a9731da-ce44-4103-9aa2-d618b388aa26">

PS: This only happens when adding a codeblock via the ``` shortcut

https://github.com/hyvor/HyvorBlogs/assets/44988673/ee2fcd7f-02a7-4d3c-9cd9-a08ef13fa6cc

**Comment by Nolab0** [comment]
Fix in https://github.com/hyvor/HyvorBlogs/commit/98a06c00cb9501496b95dc3e178ad055fcf8c7de
