### ISSUE TITLE
Config code block issue

### ISSUE THREAD

**Issue by supun-io** [hyvor/blogs#271]
Probably after our code block update, the `/config` code block no longer takes 100% height.

- [x] Fix height

<img width="1440" alt="image" src="https://github.com/hyvor/HyvorBlogs/assets/44988673/a83432f1-32f5-467e-9be1-9ce728be8c5b">

**Comment by Nolab0** [comment]
Fix by https://github.com/hyvor/HyvorBlogs/tree/80fc338bc8224dfaca3172642e5bab54d769f89e
