### ISSUE TITLE
Image Uploading Toggle issue

### ISSUE THREAD

**Issue by IshiniAvindya** [hyvor/blogs#296]
Image Uploading in the editor is not toggling when the mouse click is given. It only toggles when Enter is hit.

Uploading Screen Recording 2023-12-08 at 19.59.25.mov…

**Comment by IshiniAvindya** [comment]
https://github.com/hyvor/blogs.hyvor.com/assets/61535113/830ecaaf-f47f-4018-a1f1-f722048276da

**Comment by supun-io** [comment]
I'm closing this issue assuming this is fixed in the new version.
