### ISSUE TITLE
Settings section

### ISSUE THREAD

**Issue by supun-io** [hyvor/blogs#305]
### Set up

- [x] Take a branch from `sveltekitnew` branch
- [x] Run `npm run dev` in `frontend` (localhost:2210)
- [x] Run `composer serve` in `backend` (localhost:2211)
- [x] Set env `APP_URL=http://localhost:2211`

### Redirects

Settings -> Redirects

#### Create

- [x] Show a "Create Redirect +" button at the top

Something like this (bottom border needed):

![image](https://github.com/hyvor/blogs.hyvor.com/assets/44988673/5f2b197f-e573-4b14-b2b0-cc603501528f)

- [x] Clicking the button should open a modal. See https://hyvor-design.pages.dev/modal
- [x] Use [SplitControl](https://hyvor-design.pages.dev/split-control) in the form
- [x] Do input validation Use https://hyvor-design.pages.dev/form-control#validation (explained below)
- [x] ~~Use toasts for creating~~ https://hyvor-design.pages.dev/toast#examples
- [x] Use modal loading (https://hyvor-design.pages.dev/modal#loading) for loading state, toast for error

#### Input Validation

Validate when the add button is clicked. 

- [x] From value should start with `/` (message: `From value should be a relative path starting with /`)
- [x] To value can be anything (so no validation needed)
- [x] Type is restricted, so no validation needed there as well.

#### Display

- [x] When no redirects, use IconMessage empty screen (https://hyvor-design.pages.dev/icon-message)
- [x] When has redirects, show the table (use https://hyvor-design.pages.dev/table). The table details are the same as the old table.

<img width="837" alt="image" src="https://github.com/hyvor/blogs.hyvor.com/assets/44988673/cdfd53a5-00d2-4c2e-8942-9cc677268b98">

**Comment by Nolab0** [comment]
https://github.com/hyvor/blogs.hyvor.com/pull/307
