### ISSUE TITLE
Link Analyzer

### ISSUE THREAD

**Issue by IshiniAvindya** [hyvor/blogs#306]
In link analyzer, the following labels including broken links labels should be navigatable. Each one of them should lead to relevant links.
<img width="481" alt="Screenshot 2024-01-05 at 09 29 55" src="https://github.com/hyvor/blogs.hyvor.com/assets/61535113/db32e720-acb7-4ac9-9523-9cb72cc1be6d">

**Comment by supun-io** [comment]
Fixed in the new version
