### ISSUE TITLE
Support Timelines

### ISSUE THREAD

**Issue by Nadil-K** [hyvor/blogs#493]
https://app.crisp.chat/website/1cab78fb-4baf-497e-a10f-00a3b12cfcfe/inbox/session_53e51b7b-86f5-499f-82a2-54d7f6455db3

![image](https://github.com/user-attachments/assets/a7af3233-e2b7-4f9f-8bfb-8358bbae8892)

**Comment by supun-io** [comment]
Not implementing since it's too specific/niche
